name: Deploy and Verify

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Check for 'safe to deploy' label
        id: check_label
        run: |
          echo "Event name: ${{ github.event_name }}"
          if [[ ${{ contains(github.event.pull_request.labels.*.name, 'safe to deploy') }} == 'true' ]]; then
            echo "safe_to_deploy=true" >> $GITHUB_OUTPUT
          else
            echo "safe_to_deploy=false" >> $GITHUB_OUTPUT
          fi

      - name: Check for Modal secrets
        id: check_secrets
        if: steps.check_label.outputs.safe_to_deploy == 'true'
        run: |
          if [ -z "${{ secrets.MODAL_TOKEN_ID }}" ] || [ -z "${{ secrets.MODAL_TOKEN_SECRET }}" ]; then
            echo "modal_secrets_set=false" >> $GITHUB_OUTPUT
          else
            echo "modal_secrets_set=true" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to dev
        if: steps.check_label.outputs.safe_to_deploy == 'true' && steps.check_secrets.outputs.modal_secrets_set == 'true'
        env:
          MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
          CHEMENV_NAME: ${{ github.event_name == 'workflow_dispatch' && '-dev' || '' }}
        run: |
          echo "Deploying to dev with CHEMENV_NAME=${{ env.CHEMENV_NAME }}..."
          poetry run chemenv deploy

      - name: Run post-deployment tests
        if: steps.check_label.outputs.safe_to_deploy == 'true' && steps.check_secrets.outputs.modal_secrets_set == 'true'
        env:
          MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
          CHEMENV_NAME: ${{ github.event_name == 'workflow_dispatch' && '-dev' || '' }}
        run: |
          echo "Running post-deployment tests with CHEMENV_NAME=${{ env.CHEMENV_NAME }}..."
          poetry run pytest tests/test_modal.py
