name: Deploy and Verify

on:
  pull_request_target:
    types: [labeled, synchronize]
  push:
    branches:
      - main

jobs:
  deploy_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run pre-deployment tests
        if: steps.check_label.outputs.safe_to_deploy == 'true'
        run: poetry run pytest tests --ignore=tests/test_modal.py

      - name: Check for 'safe to deploy' label
        id: check_label
        run: |
          if [[ "${{ github.event_name }}" == "pull_request_target" ]]; then
            echo "safe_to_deploy=${{ contains(github.event.pull_request.labels.*.name, 'safe to deploy') }}" >> $GITHUB_OUTPUT
          else
            echo "safe_to_deploy=true" >> $GITHUB_OUTPUT
          fi

      - name: Check for Modal secrets
        id: check_secrets
        if: steps.check_label.outputs.safe_to_deploy == 'true'
        run: |
          if [ -z "${{ secrets.MODAL_TOKEN_ID }}" ] || [ -z "${{ secrets.MODAL_TOKEN_SECRET }}" ]; then
            echo "modal_secrets_set=false" >> $GITHUB_OUTPUT
          else
            echo "modal_secrets_set=true" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to dev
        if: steps.check_label.outputs.safe_to_deploy == 'true' && steps.check_secrets.outputs.modal_secrets_set == 'true'
        env:
          MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
        run: poetry run chemenv deploy

      - name: Run post-deployment tests
        if: steps.check_label.outputs.safe_to_deploy == 'true' && steps.check_secrets.outputs.modal_secrets_set == 'true'
        env:
          MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
        run: poetry run pytest tests/test_modal.py

      - name: Workflow summary
        run: |
          echo "Workflow Summary:"
          echo "Safe to deploy: ${{ steps.check_label.outputs.safe_to_deploy }}"
          echo "Modal secrets set: ${{ steps.check_secrets.outputs.modal_secrets_set }}"
          if [ "${{ steps.check_label.outputs.safe_to_deploy }}" != "true" ]; then
            echo "The 'safe to deploy' label is not present on this pull request."
          fi
          if [ "${{ steps.check_secrets.outputs.modal_secrets_set }}" != "true" ]; then
            echo "Modal secrets are not properly set."
          fi
